from typing import List, Dict, Any


def generate_config(
    devices: List[Any],
    system_config: Dict[str, str],
    default_influxdb: Any = None,
    scan_cache: Dict[int, Dict] = None,
    default_scan_class: Any = None,
) -> str:
    """Generate a Telegraf configuration file from device and tag data."""

    config_path = system_config.get("telegraf_config_path", "/etc/telegraf/telegraf.conf")
    influxdb_url = system_config.get("influxdb_url", "http://localhost:8086")
    influxdb_token = system_config.get("influxdb_token", "$INFLUX_TOKEN")
    influxdb_org = system_config.get("influxdb_org", "myorg")
    influxdb_default_bucket = system_config.get("influxdb_default_bucket", "default")
    app_title = system_config.get("app_title", "FluxForge")

    # Agent settings
    round_interval = system_config.get("agent_round_interval", "true").lower() == "true"
    metric_batch_size = system_config.get("agent_metric_batch_size", "1000")
    metric_buffer_limit = system_config.get("agent_metric_buffer_limit", "10000")
    collection_jitter = system_config.get("agent_collection_jitter", "0s")
    flush_interval = system_config.get("agent_flush_interval", "10s")
    flush_jitter = system_config.get("agent_flush_jitter", "0s")
    hostname = system_config.get("agent_hostname", "")
    omit_hostname = system_config.get("agent_omit_hostname", "false").lower() == "true"

    # Agent interval from default scan class
    default_interval_ms = default_scan_class.interval_ms if default_scan_class else 1000
    agent_interval = _ms_to_duration(default_interval_ms)

    lines = []
    lines.append(f"# Telegraf Configuration")
    lines.append(f"# Generated by {app_title}")
    lines.append(f"# Config path: {config_path}")
    lines.append("")

    lines.append("[agent]")
    lines.append(f'  interval = "{agent_interval}"')
    lines.append(f"  round_interval = {str(round_interval).lower()}")
    lines.append(f"  metric_batch_size = {metric_batch_size}")
    lines.append(f"  metric_buffer_limit = {metric_buffer_limit}")
    lines.append(f'  collection_jitter = "{collection_jitter}"')
    lines.append(f'  flush_interval = "{flush_interval}"')
    lines.append(f'  flush_jitter = "{flush_jitter}"')
    lines.append('  precision = ""')
    lines.append(f'  hostname = "{hostname}"')
    lines.append(f"  omit_hostname = {str(omit_hostname).lower()}")
    lines.append("")

    # Collect all unique InfluxDB targets
    influx_targets: Dict[int, Any] = {}
    for device in devices:
        if not device.enabled:
            continue
        if device.influxdb_config:
            cfg = device.influxdb_config
            influx_targets[cfg.id] = cfg
        elif default_influxdb:
            influx_targets[default_influxdb.id] = default_influxdb

    if not influx_targets:
        # Use system-level defaults
        lines.append("[[outputs.influxdb_v2]]")
        lines.append(f'  urls = ["{influxdb_url}"]')
        lines.append(f'  token = "{influxdb_token}"')
        lines.append(f'  organization = "{influxdb_org}"')
        lines.append(f'  bucket = "{influxdb_default_bucket}"')
        lines.append("")
    else:
        for cfg in influx_targets.values():
            lines.append("[[outputs.influxdb_v2]]")
            lines.append(f'  urls = ["{cfg.url}"]')
            lines.append(f'  token = "{cfg.token}"')
            lines.append(f'  organization = "{cfg.org}"')
            lines.append(f'  bucket = "{cfg.bucket}"')
            lines.append("")

    # OPC UA inputs per device
    cache = scan_cache or {}

    for device in devices:
        if not device.enabled:
            continue

        safe_name = device.name.replace(" ", "_")
        enabled_tags = [t for t in device.tags if t.enabled]
        emitted_node_ids: set = set()

        # Expand enabled NodeIncludes into pseudo-tag dicts
        expanded_from_includes: List[Dict] = []
        node_includes = getattr(device, "node_includes", [])
        enabled_includes = [ni for ni in node_includes if ni.enabled]
        if enabled_includes:
            cached = cache.get(device.id, {})
            cached_nodes = cached.get("nodes", []) if cached.get("status") == "complete" else []
            if not cached_nodes:
                for ni in enabled_includes:
                    lines.append(f"# WARNING: Branch subscription '{ni.parent_path}' on {device.name}"
                                 " could not be expanded (no scan data available)")
            else:
                for ni in enabled_includes:
                    prefix = ni.parent_path + "/"
                    for node in cached_nodes:
                        node_path = node.get("path", "")
                        if node_path.startswith(prefix) or node_path == ni.parent_path:
                            expanded_from_includes.append({
                                "node_id": node["node_id"],
                                "display_name": node["display_name"],
                                "namespace": node["namespace"],
                                "identifier": node["identifier"],
                                "identifier_type": node.get("identifier_type", "s"),
                                "measurement_name": ni.measurement_name,
                                "scan_class": ni.scan_class,
                                "scan_class_id": ni.scan_class_id,
                                "path": node.get("path", ""),
                            })

        # Build combined tag list grouped by scan class
        by_scan_class: Dict[str, List[Any]] = {}

        for tag in sorted(enabled_tags, key=lambda t: (t.path or "", t.display_name)):
            sc_name = tag.scan_class.name if tag.scan_class else "default"
            by_scan_class.setdefault(sc_name, []).append({
                "node_id": tag.node_id,
                "display_name": tag.display_name,
                "namespace": tag.namespace,
                "identifier": tag.identifier,
                "identifier_type": tag.identifier_type,
                "measurement_name": tag.measurement_name,
                "scan_class": tag.scan_class,
                "path": tag.path or "",
            })
            emitted_node_ids.add(tag.node_id)

        # Add expanded includes, deduplicating against individual tags
        for etag in sorted(expanded_from_includes, key=lambda t: (t.get("path", ""), t["display_name"])):
            if etag["node_id"] in emitted_node_ids:
                continue
            emitted_node_ids.add(etag["node_id"])
            sc_name = etag["scan_class"].name if etag.get("scan_class") else "default"
            by_scan_class.setdefault(sc_name, []).append(etag)

        if not by_scan_class:
            continue

        for sc_name, tags in by_scan_class.items():
            sc = tags[0].get("scan_class") if isinstance(tags[0], dict) else tags[0].scan_class
            interval_ms = sc.interval_ms if sc else 1000
            interval_str = _ms_to_duration(interval_ms)

            lines.append("[[inputs.opcua]]")
            lines.append(f'  name = "{safe_name}_{sc_name}"')
            lines.append(f'  endpoint = "{device.endpoint_url}"')
            if device.username:
                lines.append(f'  username = "{device.username}"')
                lines.append(f'  password = "{device.password}"')
            lines.append(f'  security_policy = "{device.security_policy or "None"}"')
            if interval_ms != default_interval_ms:
                lines.append(f'  interval = "{interval_str}"')
            lines.append("")

            # Sub-group tags by (measurement, namespace, identifier_type)
            groups: Dict[tuple, List] = {}
            for tag in sorted(tags, key=lambda t: (t.get("path", ""), t.get("display_name", ""))):
                if isinstance(tag, dict):
                    measurement = tag["measurement_name"] or safe_name
                    ns = tag["namespace"]
                    id_type = tag["identifier_type"]
                else:
                    measurement = tag.measurement_name or safe_name
                    ns = tag.namespace
                    id_type = tag.identifier_type
                group_key = (measurement, str(ns), id_type)
                groups.setdefault(group_key, []).append(tag)

            for (measurement, ns, id_type), group_tags in groups.items():
                lines.append("  [[inputs.opcua.group]]")
                lines.append(f'    name = "{measurement}"')
                lines.append(f'    namespace = "{ns}"')
                lines.append(f'    identifier_type = "{id_type}"')
                lines.append(f'    default_tags = {{scanClass = "{sc_name}"}}')
                lines.append("")

                for tag in group_tags:
                    display = (tag["display_name"] if isinstance(tag, dict) else tag.display_name).replace(" ", "_")
                    identifier = tag["identifier"] if isinstance(tag, dict) else tag.identifier
                    lines.append("    [[inputs.opcua.group.nodes]]")
                    lines.append(f'      name = "{display}"')
                    lines.append(f'      identifier = "{identifier}"')
                    lines.append("")

        lines.append("")

    # Append passthrough sections (imported non-OPC-UA config)
    passthrough = system_config.get("telegraf_passthrough", "")
    if passthrough and passthrough.strip():
        lines.append("# " + "─" * 50)
        lines.append("# Passthrough sections (imported from config)")
        lines.append("# " + "─" * 50)
        lines.append("")
        lines.append(passthrough.strip())
        lines.append("")

    return "\n".join(lines)


def _ms_to_duration(ms: int) -> str:
    if ms < 1000:
        return f"{ms}ms"
    seconds = ms // 1000
    if seconds < 60:
        return f"{seconds}s"
    minutes = seconds // 60
    if minutes < 60:
        return f"{minutes}m"
    hours = minutes // 60
    return f"{hours}h"
