from typing import List, Dict, Any


def generate_config(
    devices: List[Any],
    system_config: Dict[str, str],
    default_influxdb: Any = None,
    scan_cache: Dict[int, Dict] = None,
    default_scan_class: Any = None,
) -> str:
    """Generate a Telegraf configuration file from device and tag data."""

    config_path = system_config.get("telegraf_config_path", "/etc/telegraf/telegraf.conf")
    influxdb_url = system_config.get("influxdb_url", "http://localhost:8086")
    influxdb_token = system_config.get("influxdb_token", "$INFLUX_TOKEN")
    influxdb_org = system_config.get("influxdb_org", "myorg")
    influxdb_default_bucket = system_config.get("influxdb_default_bucket", "default")
    app_title = system_config.get("app_title", "FluxForge")

    # Agent settings
    round_interval = system_config.get("agent_round_interval", "true").lower() == "true"
    metric_batch_size = system_config.get("agent_metric_batch_size", "1000")
    metric_buffer_limit = system_config.get("agent_metric_buffer_limit", "10000")
    collection_jitter = system_config.get("agent_collection_jitter", "0s")
    flush_interval = system_config.get("agent_flush_interval", "10s")
    flush_jitter = system_config.get("agent_flush_jitter", "0s")
    hostname = system_config.get("agent_hostname", "")
    omit_hostname = system_config.get("agent_omit_hostname", "false").lower() == "true"

    # Agent interval from default scan class
    default_interval_ms = default_scan_class.interval_ms if default_scan_class else 1000
    agent_interval = _ms_to_duration(default_interval_ms)

    lines = []
    lines.append(f"# Telegraf Configuration")
    lines.append(f"# Generated by {app_title}")
    lines.append(f"# Config path: {config_path}")
    lines.append("")

    lines.append("[agent]")
    lines.append(f'  interval = "{agent_interval}"')
    lines.append(f"  round_interval = {str(round_interval).lower()}")
    lines.append(f"  metric_batch_size = {metric_batch_size}")
    lines.append(f"  metric_buffer_limit = {metric_buffer_limit}")
    lines.append(f'  collection_jitter = "{collection_jitter}"')
    lines.append(f'  flush_interval = "{flush_interval}"')
    lines.append(f'  flush_jitter = "{flush_jitter}"')
    lines.append('  precision = ""')
    lines.append(f'  hostname = "{hostname}"')
    lines.append(f"  omit_hostname = {str(omit_hostname).lower()}")
    lines.append("")

    # Collect all unique InfluxDB targets
    influx_targets: Dict[int, Any] = {}
    for device in devices:
        if not device.enabled:
            continue
        if device.influxdb_config:
            cfg = device.influxdb_config
            influx_targets[cfg.id] = cfg
        elif default_influxdb:
            influx_targets[default_influxdb.id] = default_influxdb

    if not influx_targets:
        # Use system-level defaults
        lines.append("[[outputs.influxdb_v2]]")
        lines.append(f'  urls = ["{influxdb_url}"]')
        lines.append(f'  token = "{influxdb_token}"')
        lines.append(f'  organization = "{influxdb_org}"')
        lines.append(f'  bucket = "{influxdb_default_bucket}"')
        if influxdb_url.startswith("https"):
            lines.append("  insecure_skip_verify = true")
        lines.append("")
    else:
        for cfg in influx_targets.values():
            lines.append("[[outputs.influxdb_v2]]")
            lines.append(f'  urls = ["{cfg.url}"]')
            lines.append(f'  token = "{cfg.token}"')
            lines.append(f'  organization = "{cfg.org}"')
            lines.append(f'  bucket = "{cfg.bucket}"')
            if cfg.url.startswith("https"):
                lines.append("  insecure_skip_verify = true")
            lines.append("")

    # OPC UA inputs per device
    cache = scan_cache or {}

    for device in devices:
        if not device.enabled:
            continue

        safe_name = device.name.replace(" ", "_")
        enabled_tags = [t for t in device.tags if t.enabled]
        emitted_node_ids: set = set()

        # Expand enabled NodeIncludes into pseudo-tag dicts
        expanded_from_includes: List[Dict] = []
        node_includes = getattr(device, "node_includes", [])
        enabled_includes = [ni for ni in node_includes if ni.enabled]
        if enabled_includes:
            cached = cache.get(device.id, {})
            cached_nodes = cached.get("nodes", []) if cached.get("status") == "complete" else []
            if not cached_nodes:
                for ni in enabled_includes:
                    lines.append(f"# WARNING: Branch subscription '{ni.parent_path}' on {device.name}"
                                 " could not be expanded (no scan data available)")
            else:
                for ni in enabled_includes:
                    prefix = ni.parent_path + "/"
                    for node in cached_nodes:
                        node_path = node.get("path", "")
                        if node_path.startswith(prefix) or node_path == ni.parent_path:
                            expanded_from_includes.append({
                                "node_id": node["node_id"],
                                "display_name": node["display_name"],
                                "namespace": node["namespace"],
                                "identifier": node["identifier"],
                                "identifier_type": node.get("identifier_type", "s"),
                                "measurement_name": ni.measurement_name,
                                "scan_class": ni.scan_class,
                                "scan_class_id": ni.scan_class_id,
                                "path": node.get("path", ""),
                            })

        # Build combined tag list grouped by scan class
        by_scan_class: Dict[str, List[Any]] = {}

        for tag in sorted(enabled_tags, key=lambda t: (t.path or "", t.display_name)):
            sc_name = tag.scan_class.name if tag.scan_class else "default"
            by_scan_class.setdefault(sc_name, []).append({
                "node_id": tag.node_id,
                "display_name": tag.display_name,
                "namespace": tag.namespace,
                "identifier": tag.identifier,
                "identifier_type": tag.identifier_type,
                "measurement_name": tag.measurement_name,
                "scan_class": tag.scan_class,
                "path": tag.path or "",
            })
            emitted_node_ids.add(tag.node_id)

        # Add expanded includes, deduplicating against individual tags
        for etag in sorted(expanded_from_includes, key=lambda t: (t.get("path", ""), t["display_name"])):
            if etag["node_id"] in emitted_node_ids:
                continue
            emitted_node_ids.add(etag["node_id"])
            sc_name = etag["scan_class"].name if etag.get("scan_class") else "default"
            by_scan_class.setdefault(sc_name, []).append(etag)

        if not by_scan_class:
            continue

        for sc_name, tags in by_scan_class.items():
            sc = tags[0].get("scan_class") if isinstance(tags[0], dict) else tags[0].scan_class
            interval_ms = sc.interval_ms if sc else 1000
            interval_str = _ms_to_duration(interval_ms)

            lines.append("[[inputs.opcua]]")
            lines.append(f'  name = "{safe_name}_{sc_name}"')
            lines.append(f'  endpoint = "{device.endpoint_url}"')
            if device.username:
                lines.append(f'  username = "{device.username}"')
                lines.append(f'  password = "{device.password}"')
            sec_policy = device.security_policy or "None"
            lines.append(f'  security_policy = "{sec_policy}"')
            if sec_policy == "None":
                lines.append('  security_mode = "None"')
            else:
                lines.append(f'  certificate = "/app/data/opcua_client_cert.pem"')
                lines.append(f'  private_key = "/app/data/opcua_client_key.pem"')
            if interval_ms != default_interval_ms:
                lines.append(f'  interval = "{interval_str}"')
            lines.append("")

            # Sub-group tags by (measurement, namespace, identifier_type)
            groups: Dict[tuple, List] = {}
            for tag in sorted(tags, key=lambda t: (t.get("path", ""), t.get("display_name", ""))):
                if isinstance(tag, dict):
                    measurement = tag["measurement_name"] or safe_name
                    ns = tag["namespace"]
                    id_type = tag["identifier_type"]
                else:
                    measurement = tag.measurement_name or safe_name
                    ns = tag.namespace
                    id_type = tag.identifier_type
                group_key = (measurement, str(ns), id_type)
                groups.setdefault(group_key, []).append(tag)

            for (measurement, ns, id_type), group_tags in groups.items():
                lines.append("  [[inputs.opcua.group]]")
                lines.append(f'    name = "{measurement}"')
                lines.append(f'    namespace = "{ns}"')
                lines.append(f'    identifier_type = "{id_type}"')
                lines.append(f'    default_tags = {{scanClass = "{sc_name}"}}')
                lines.append("")

                for tag in group_tags:
                    display = (tag["display_name"] if isinstance(tag, dict) else tag.display_name).replace(" ", "_")
                    identifier = tag["identifier"] if isinstance(tag, dict) else tag.identifier
                    lines.append("    [[inputs.opcua.group.nodes]]")
                    lines.append(f'      name = "{display}"')
                    lines.append(f'      identifier = "{identifier}"')
                    lines.append("")

        lines.append("")

    # Append passthrough sections (imported non-OPC-UA config)
    passthrough = system_config.get("telegraf_passthrough", "")
    if passthrough and passthrough.strip():
        lines.append("# " + "─" * 50)
        lines.append("# Passthrough sections (imported from config)")
        lines.append("# " + "─" * 50)
        lines.append("")
        lines.append(passthrough.strip())
        lines.append("")

    return "\n".join(lines)


def generate_config_from_tags(
    tags: List[Any],
    system_config: Dict[str, str],
    default_influxdb: Any = None,
    scan_cache: Dict[int, Dict] = None,
    default_scan_class: Any = None,
) -> str:
    """Generate a Telegraf config from a flat list of Tag objects (per-tag instance assignment).

    Tags must have .device relationship loaded (with .influxdb_config).
    """
    app_title = system_config.get("app_title", "FluxForge")
    config_path = system_config.get("telegraf_config_path", "/etc/telegraf/telegraf.conf")
    influxdb_url = system_config.get("influxdb_url", "http://localhost:8086")
    influxdb_token = system_config.get("influxdb_token", "$INFLUX_TOKEN")
    influxdb_org = system_config.get("influxdb_org", "myorg")
    influxdb_default_bucket = system_config.get("influxdb_default_bucket", "default")

    round_interval = system_config.get("agent_round_interval", "true").lower() == "true"
    metric_batch_size = system_config.get("agent_metric_batch_size", "1000")
    metric_buffer_limit = system_config.get("agent_metric_buffer_limit", "10000")
    collection_jitter = system_config.get("agent_collection_jitter", "0s")
    flush_interval = system_config.get("agent_flush_interval", "10s")
    flush_jitter = system_config.get("agent_flush_jitter", "0s")
    hostname = system_config.get("agent_hostname", "")
    omit_hostname = system_config.get("agent_omit_hostname", "false").lower() == "true"

    default_interval_ms = default_scan_class.interval_ms if default_scan_class else 1000
    agent_interval = _ms_to_duration(default_interval_ms)

    lines = []
    lines.append(f"# Telegraf Configuration")
    lines.append(f"# Generated by {app_title}")
    lines.append(f"# Config path: {config_path}")
    lines.append("")

    lines.append("[agent]")
    lines.append(f'  interval = "{agent_interval}"')
    lines.append(f"  round_interval = {str(round_interval).lower()}")
    lines.append(f"  metric_batch_size = {metric_batch_size}")
    lines.append(f"  metric_buffer_limit = {metric_buffer_limit}")
    lines.append(f'  collection_jitter = "{collection_jitter}"')
    lines.append(f'  flush_interval = "{flush_interval}"')
    lines.append(f'  flush_jitter = "{flush_jitter}"')
    lines.append('  precision = ""')
    lines.append(f'  hostname = "{hostname}"')
    lines.append(f"  omit_hostname = {str(omit_hostname).lower()}")
    lines.append("")

    # Group tags by device
    by_device: Dict[int, List[Any]] = {}
    devices_map: Dict[int, Any] = {}
    for tag in tags:
        by_device.setdefault(tag.device_id, []).append(tag)
        if tag.device_id not in devices_map:
            devices_map[tag.device_id] = tag.device

    # Collect InfluxDB targets
    influx_targets: Dict[int, Any] = {}
    for device in devices_map.values():
        if not device.enabled:
            continue
        if device.influxdb_config:
            influx_targets[device.influxdb_config.id] = device.influxdb_config
        elif default_influxdb:
            influx_targets[default_influxdb.id] = default_influxdb

    if not influx_targets:
        lines.append("[[outputs.influxdb_v2]]")
        lines.append(f'  urls = ["{influxdb_url}"]')
        lines.append(f'  token = "{influxdb_token}"')
        lines.append(f'  organization = "{influxdb_org}"')
        lines.append(f'  bucket = "{influxdb_default_bucket}"')
        if influxdb_url.startswith("https"):
            lines.append("  insecure_skip_verify = true")
        lines.append("")
    else:
        for cfg in influx_targets.values():
            lines.append("[[outputs.influxdb_v2]]")
            lines.append(f'  urls = ["{cfg.url}"]')
            lines.append(f'  token = "{cfg.token}"')
            lines.append(f'  organization = "{cfg.org}"')
            lines.append(f'  bucket = "{cfg.bucket}"')
            if cfg.url.startswith("https"):
                lines.append("  insecure_skip_verify = true")
            lines.append("")

    # OPC UA inputs per device
    for device_id, device_tags in by_device.items():
        device = devices_map[device_id]
        if not device.enabled:
            continue

        safe_name = device.name.replace(" ", "_")

        # Group by scan class
        by_scan_class: Dict[str, List[Any]] = {}
        for tag in sorted(device_tags, key=lambda t: (t.path or "", t.display_name)):
            sc_name = tag.scan_class.name if tag.scan_class else "default"
            by_scan_class.setdefault(sc_name, []).append(tag)

        for sc_name, sc_tags in by_scan_class.items():
            sc = sc_tags[0].scan_class
            interval_ms = sc.interval_ms if sc else 1000
            interval_str = _ms_to_duration(interval_ms)

            lines.append("[[inputs.opcua]]")
            lines.append(f'  name = "{safe_name}_{sc_name}"')
            lines.append(f'  endpoint = "{device.endpoint_url}"')
            if device.username:
                lines.append(f'  username = "{device.username}"')
                lines.append(f'  password = "{device.password}"')
            sec_policy = device.security_policy or "None"
            lines.append(f'  security_policy = "{sec_policy}"')
            if sec_policy == "None":
                lines.append('  security_mode = "None"')
            else:
                lines.append(f'  certificate = "/app/data/opcua_client_cert.pem"')
                lines.append(f'  private_key = "/app/data/opcua_client_key.pem"')
            if interval_ms != default_interval_ms:
                lines.append(f'  interval = "{interval_str}"')
            lines.append("")

            # Sub-group by (measurement, namespace, identifier_type)
            groups: Dict[tuple, List] = {}
            for tag in sorted(sc_tags, key=lambda t: (t.path or "", t.display_name)):
                measurement = tag.measurement_name or safe_name
                group_key = (measurement, str(tag.namespace), tag.identifier_type)
                groups.setdefault(group_key, []).append(tag)

            for (measurement, ns, id_type), group_tags in groups.items():
                lines.append("  [[inputs.opcua.group]]")
                lines.append(f'    name = "{measurement}"')
                lines.append(f'    namespace = "{ns}"')
                lines.append(f'    identifier_type = "{id_type}"')
                lines.append(f'    default_tags = {{scanClass = "{sc_name}"}}')
                lines.append("")

                for tag in group_tags:
                    display = tag.display_name.replace(" ", "_")
                    lines.append("    [[inputs.opcua.group.nodes]]")
                    lines.append(f'      name = "{display}"')
                    lines.append(f'      identifier = "{tag.identifier}"')
                    lines.append("")

        lines.append("")

    # Passthrough sections
    passthrough = system_config.get("telegraf_passthrough", "")
    if passthrough and passthrough.strip():
        lines.append("# " + "─" * 50)
        lines.append("# Passthrough sections (imported from config)")
        lines.append("# " + "─" * 50)
        lines.append("")
        lines.append(passthrough.strip())
        lines.append("")

    return "\n".join(lines)


def generate_instance_configs(
    instances: List[Any],
    system_config: Dict[str, str],
    default_influxdb: Any = None,
    scan_cache: Dict[int, Dict] = None,
    default_scan_class: Any = None,
) -> Dict[int, Dict[str, Any]]:
    """Generate configs for each TelegrafInstance.

    Returns {instance_id: {"name": str, "config": str, "device_count": int, "tag_count": int}}
    """
    result = {}
    for instance in instances:
        devices = [d for d in instance.devices if d.enabled]
        tag_count = sum(
            len([t for t in d.tags if t.enabled]) for d in devices
        )
        config = generate_config(
            devices, system_config, default_influxdb,
            scan_cache=scan_cache, default_scan_class=default_scan_class,
        )
        result[instance.id] = {
            "name": instance.name,
            "config": config,
            "device_count": len(devices),
            "tag_count": tag_count,
        }
    return result


def suggest_splits(
    devices: List[Any],
    max_tags_per_instance: int = 5000,
) -> List[Dict[str, Any]]:
    """Analyze devices and suggest groupings based on tag counts and scan rates.

    Returns a list of suggestions: [{name, device_ids, device_names, tag_count, reason}]
    """
    suggestions = []

    # Build per-device stats
    device_stats = []
    for d in devices:
        if not d.enabled:
            continue
        enabled_tags = [t for t in d.tags if t.enabled]
        tag_count = len(enabled_tags)
        # Find the fastest scan rate among this device's tags
        min_interval = None
        for t in enabled_tags:
            if t.scan_class and t.scan_class.interval_ms:
                if min_interval is None or t.scan_class.interval_ms < min_interval:
                    min_interval = t.scan_class.interval_ms
        device_stats.append({
            "id": d.id,
            "name": d.name,
            "tag_count": tag_count,
            "min_interval_ms": min_interval,
        })

    total_tags = sum(ds["tag_count"] for ds in device_stats)

    if total_tags <= max_tags_per_instance and len(device_stats) <= 1:
        return []

    # Strategy 1: If total tags exceed threshold, suggest per-device split
    if total_tags > max_tags_per_instance:
        for ds in device_stats:
            safe = ds["name"].lower().replace(" ", "-")
            suggestions.append({
                "name": f"telegraf-{safe}",
                "device_ids": [ds["id"]],
                "device_names": [ds["name"]],
                "tag_count": ds["tag_count"],
                "reason": f"Total tags ({total_tags}) exceed threshold ({max_tags_per_instance}). "
                          f"Splitting {ds['name']} ({ds['tag_count']} tags) into its own instance.",
            })
        return suggestions

    # Strategy 2: Group by scan rate similarity
    fast_devices = [ds for ds in device_stats if ds["min_interval_ms"] and ds["min_interval_ms"] < 500]
    slow_devices = [ds for ds in device_stats if not ds["min_interval_ms"] or ds["min_interval_ms"] >= 500]

    if fast_devices and slow_devices:
        fast_tags = sum(ds["tag_count"] for ds in fast_devices)
        slow_tags = sum(ds["tag_count"] for ds in slow_devices)
        suggestions.append({
            "name": "telegraf-fast",
            "device_ids": [ds["id"] for ds in fast_devices],
            "device_names": [ds["name"] for ds in fast_devices],
            "tag_count": fast_tags,
            "reason": f"Devices with fast scan rates (<500ms): {fast_tags} tags",
        })
        suggestions.append({
            "name": "telegraf-standard",
            "device_ids": [ds["id"] for ds in slow_devices],
            "device_names": [ds["name"] for ds in slow_devices],
            "tag_count": slow_tags,
            "reason": f"Devices with standard scan rates (>=500ms): {slow_tags} tags",
        })
        return suggestions

    # Strategy 3: Multiple devices, suggest per-device
    if len(device_stats) > 1:
        for ds in device_stats:
            safe = ds["name"].lower().replace(" ", "-")
            suggestions.append({
                "name": f"telegraf-{safe}",
                "device_ids": [ds["id"]],
                "device_names": [ds["name"]],
                "tag_count": ds["tag_count"],
                "reason": f"One instance per device for fault isolation",
            })

    return suggestions


def _ms_to_duration(ms: int) -> str:
    if ms < 1000:
        return f"{ms}ms"
    seconds = ms // 1000
    if seconds < 60:
        return f"{seconds}s"
    minutes = seconds // 60
    if minutes < 60:
        return f"{minutes}m"
    hours = minutes // 60
    return f"{hours}h"
